package com.elichn.pub.core.model.mapper.security;

import com.elichn.pub.core.model.pojo.security.SeRescRoleExample;
import com.elichn.pub.core.model.pojo.security.SeRescRoleKey;
import java.util.List;
import org.apache.ibatis.annotations.Delete;
import org.apache.ibatis.annotations.Insert;
import org.apache.ibatis.annotations.Param;

public interface SeRescRoleMapper {
    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table se_resc_role
     *
     * @mbggenerated Sun Oct 29 22:40:02 CST 2017
     */
    int countByExample(SeRescRoleExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table se_resc_role
     *
     * @mbggenerated Sun Oct 29 22:40:02 CST 2017
     */
    int deleteByExample(SeRescRoleExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table se_resc_role
     *
     * @mbggenerated Sun Oct 29 22:40:02 CST 2017
     */
    @Delete({
        "delete from se_resc_role",
        "where resc_id = #{rescId,jdbcType=INTEGER}",
          "and role_id = #{roleId,jdbcType=INTEGER}"
    })
    int deleteByPrimaryKey(SeRescRoleKey key);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table se_resc_role
     *
     * @mbggenerated Sun Oct 29 22:40:02 CST 2017
     */
    @Insert({
        "insert into se_resc_role (resc_id, role_id)",
        "values (#{rescId,jdbcType=INTEGER}, #{roleId,jdbcType=INTEGER})"
    })
    int insert(SeRescRoleKey record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table se_resc_role
     *
     * @mbggenerated Sun Oct 29 22:40:02 CST 2017
     */
    int insertSelective(SeRescRoleKey record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table se_resc_role
     *
     * @mbggenerated Sun Oct 29 22:40:02 CST 2017
     */
    List<SeRescRoleKey> selectByExample(SeRescRoleExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table se_resc_role
     *
     * @mbggenerated Sun Oct 29 22:40:02 CST 2017
     */
    int updateByExampleSelective(@Param("record") SeRescRoleKey record, @Param("example") SeRescRoleExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table se_resc_role
     *
     * @mbggenerated Sun Oct 29 22:40:02 CST 2017
     */
    int updateByExample(@Param("record") SeRescRoleKey record, @Param("example") SeRescRoleExample example);
}