package com.elichn.pub.core.model.mapper.security;

import com.elichn.pub.core.model.pojo.security.SeUser;
import com.elichn.pub.core.model.pojo.security.SeUserExample;
import java.util.List;
import org.apache.ibatis.annotations.Delete;
import org.apache.ibatis.annotations.Insert;
import org.apache.ibatis.annotations.Param;
import org.apache.ibatis.annotations.ResultMap;
import org.apache.ibatis.annotations.Select;
import org.apache.ibatis.annotations.SelectKey;
import org.apache.ibatis.annotations.Update;

public interface SeUserMapper {
    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table se_user
     *
     * @mbggenerated Sun Oct 29 22:40:27 CST 2017
     */
    int countByExample(SeUserExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table se_user
     *
     * @mbggenerated Sun Oct 29 22:40:27 CST 2017
     */
    int deleteByExample(SeUserExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table se_user
     *
     * @mbggenerated Sun Oct 29 22:40:27 CST 2017
     */
    @Delete({
        "delete from se_user",
        "where id = #{id,jdbcType=INTEGER}"
    })
    int deleteByPrimaryKey(Integer id);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table se_user
     *
     * @mbggenerated Sun Oct 29 22:40:27 CST 2017
     */
    @Insert({
        "insert into se_user (username, cn_name, ",
        "password, status, ",
        "user_type, descn, ",
        "email, create_time)",
        "values (#{username,jdbcType=VARCHAR}, #{cnName,jdbcType=VARCHAR}, ",
        "#{password,jdbcType=VARCHAR}, #{status,jdbcType=INTEGER}, ",
        "#{userType,jdbcType=INTEGER}, #{descn,jdbcType=VARCHAR}, ",
        "#{email,jdbcType=VARCHAR}, #{createTime,jdbcType=TIMESTAMP,typeHandler=com.elichn.mybatis.typehandler.JodaDateTime2TimestampTypeHandler})"
    })
    @SelectKey(statement="SELECT LAST_INSERT_ID()", keyProperty="id", before=false, resultType=Integer.class)
    int insert(SeUser record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table se_user
     *
     * @mbggenerated Sun Oct 29 22:40:27 CST 2017
     */
    int insertSelective(SeUser record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table se_user
     *
     * @mbggenerated Sun Oct 29 22:40:27 CST 2017
     */
    List<SeUser> selectByExample(SeUserExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table se_user
     *
     * @mbggenerated Sun Oct 29 22:40:27 CST 2017
     */
    @Select({
        "select",
        "id, username, cn_name, password, status, user_type, descn, email, create_time",
        "from se_user",
        "where id = #{id,jdbcType=INTEGER}"
    })
    @ResultMap("BaseResultMap")
    SeUser selectByPrimaryKey(Integer id);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table se_user
     *
     * @mbggenerated Sun Oct 29 22:40:27 CST 2017
     */
    int updateByExampleSelective(@Param("record") SeUser record, @Param("example") SeUserExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table se_user
     *
     * @mbggenerated Sun Oct 29 22:40:27 CST 2017
     */
    int updateByExample(@Param("record") SeUser record, @Param("example") SeUserExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table se_user
     *
     * @mbggenerated Sun Oct 29 22:40:27 CST 2017
     */
    int updateByPrimaryKeySelective(SeUser record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table se_user
     *
     * @mbggenerated Sun Oct 29 22:40:27 CST 2017
     */
    @Update({
        "update se_user",
        "set username = #{username,jdbcType=VARCHAR},",
          "cn_name = #{cnName,jdbcType=VARCHAR},",
          "password = #{password,jdbcType=VARCHAR},",
          "status = #{status,jdbcType=INTEGER},",
          "user_type = #{userType,jdbcType=INTEGER},",
          "descn = #{descn,jdbcType=VARCHAR},",
          "email = #{email,jdbcType=VARCHAR},",
          "create_time = #{createTime,jdbcType=TIMESTAMP,typeHandler=com.elichn.mybatis.typehandler.JodaDateTime2TimestampTypeHandler}",
        "where id = #{id,jdbcType=INTEGER}"
    })
    int updateByPrimaryKey(SeUser record);
}