package com.elichn.pub.core.model.pub.pojo.security;

import java.io.Serializable;
import org.joda.time.DateTime;

public class SeLog implements Serializable {
    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column se_log.id
     *
     * @mbggenerated Sun Oct 29 22:39:39 CST 2017
     */
    private Integer id;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column se_log.ip
     *
     * @mbggenerated Sun Oct 29 22:39:39 CST 2017
     */
    private String ip;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column se_log.user_name
     *
     * @mbggenerated Sun Oct 29 22:39:39 CST 2017
     */
    private String userName;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column se_log.log_type
     *
     * @mbggenerated Sun Oct 29 22:39:39 CST 2017
     */
    private String logType;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column se_log.log_content
     *
     * @mbggenerated Sun Oct 29 22:39:39 CST 2017
     */
    private String logContent;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column se_log.log_time
     *
     * @mbggenerated Sun Oct 29 22:39:39 CST 2017
     */
    private DateTime logTime;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database table se_log
     *
     * @mbggenerated Sun Oct 29 22:39:39 CST 2017
     */
    private static final long serialVersionUID = 1L;

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column se_log.id
     *
     * @return the value of se_log.id
     *
     * @mbggenerated Sun Oct 29 22:39:39 CST 2017
     */
    public Integer getId() {
        return id;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column se_log.id
     *
     * @param id the value for se_log.id
     *
     * @mbggenerated Sun Oct 29 22:39:39 CST 2017
     */
    public void setId(Integer id) {
        this.id = id;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column se_log.ip
     *
     * @return the value of se_log.ip
     *
     * @mbggenerated Sun Oct 29 22:39:39 CST 2017
     */
    public String getIp() {
        return ip;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column se_log.ip
     *
     * @param ip the value for se_log.ip
     *
     * @mbggenerated Sun Oct 29 22:39:39 CST 2017
     */
    public void setIp(String ip) {
        this.ip = ip == null ? null : ip.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column se_log.user_name
     *
     * @return the value of se_log.user_name
     *
     * @mbggenerated Sun Oct 29 22:39:39 CST 2017
     */
    public String getUserName() {
        return userName;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column se_log.user_name
     *
     * @param userName the value for se_log.user_name
     *
     * @mbggenerated Sun Oct 29 22:39:39 CST 2017
     */
    public void setUserName(String userName) {
        this.userName = userName == null ? null : userName.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column se_log.log_type
     *
     * @return the value of se_log.log_type
     *
     * @mbggenerated Sun Oct 29 22:39:39 CST 2017
     */
    public String getLogType() {
        return logType;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column se_log.log_type
     *
     * @param logType the value for se_log.log_type
     *
     * @mbggenerated Sun Oct 29 22:39:39 CST 2017
     */
    public void setLogType(String logType) {
        this.logType = logType == null ? null : logType.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column se_log.log_content
     *
     * @return the value of se_log.log_content
     *
     * @mbggenerated Sun Oct 29 22:39:39 CST 2017
     */
    public String getLogContent() {
        return logContent;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column se_log.log_content
     *
     * @param logContent the value for se_log.log_content
     *
     * @mbggenerated Sun Oct 29 22:39:39 CST 2017
     */
    public void setLogContent(String logContent) {
        this.logContent = logContent == null ? null : logContent.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column se_log.log_time
     *
     * @return the value of se_log.log_time
     *
     * @mbggenerated Sun Oct 29 22:39:39 CST 2017
     */
    public DateTime getLogTime() {
        return logTime;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column se_log.log_time
     *
     * @param logTime the value for se_log.log_time
     *
     * @mbggenerated Sun Oct 29 22:39:39 CST 2017
     */
    public void setLogTime(DateTime logTime) {
        this.logTime = logTime;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table se_log
     *
     * @mbggenerated Sun Oct 29 22:39:39 CST 2017
     */
    @Override
    public boolean equals(Object that) {
        if (this == that) {
            return true;
        }
        if (that == null) {
            return false;
        }
        if (getClass() != that.getClass()) {
            return false;
        }
        SeLog other = (SeLog) that;
        return (this.getId() == null ? other.getId() == null : this.getId().equals(other.getId()))
            && (this.getIp() == null ? other.getIp() == null : this.getIp().equals(other.getIp()))
            && (this.getUserName() == null ? other.getUserName() == null : this.getUserName().equals(other.getUserName()))
            && (this.getLogType() == null ? other.getLogType() == null : this.getLogType().equals(other.getLogType()))
            && (this.getLogContent() == null ? other.getLogContent() == null : this.getLogContent().equals(other.getLogContent()))
            && (this.getLogTime() == null ? other.getLogTime() == null : this.getLogTime().equals(other.getLogTime()));
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table se_log
     *
     * @mbggenerated Sun Oct 29 22:39:39 CST 2017
     */
    @Override
    public int hashCode() {
        final int prime = 31;
        int result = 1;
        result = prime * result + ((getId() == null) ? 0 : getId().hashCode());
        result = prime * result + ((getIp() == null) ? 0 : getIp().hashCode());
        result = prime * result + ((getUserName() == null) ? 0 : getUserName().hashCode());
        result = prime * result + ((getLogType() == null) ? 0 : getLogType().hashCode());
        result = prime * result + ((getLogContent() == null) ? 0 : getLogContent().hashCode());
        result = prime * result + ((getLogTime() == null) ? 0 : getLogTime().hashCode());
        return result;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table se_log
     *
     * @mbggenerated Sun Oct 29 22:39:39 CST 2017
     */
    @Override
    public String toString() {
        StringBuilder sb = new StringBuilder();
        sb.append(getClass().getSimpleName());
        sb.append(" [");
        sb.append("Hash = ").append(hashCode());
        sb.append(", id=").append(id);
        sb.append(", ip=").append(ip);
        sb.append(", userName=").append(userName);
        sb.append(", logType=").append(logType);
        sb.append(", logContent=").append(logContent);
        sb.append(", logTime=").append(logTime);
        sb.append(", serialVersionUID=").append(serialVersionUID);
        sb.append("]");
        return sb.toString();
    }
}