package com.elichn.pub.core.model.pub.pojo.security;

import java.io.Serializable;

public class SePublicPermission implements Serializable {
    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column se_public_permission.id
     *
     * @mbggenerated Sun Oct 29 22:39:49 CST 2017
     */
    private Integer id;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column se_public_permission.resource
     *
     * @mbggenerated Sun Oct 29 22:39:49 CST 2017
     */
    private String resource;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column se_public_permission.filter
     *
     * @mbggenerated Sun Oct 29 22:39:49 CST 2017
     */
    private String filter;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column se_public_permission.system
     *
     * @mbggenerated Sun Oct 29 22:39:49 CST 2017
     */
    private String system;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column se_public_permission.comment
     *
     * @mbggenerated Sun Oct 29 22:39:49 CST 2017
     */
    private String comment;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database table se_public_permission
     *
     * @mbggenerated Sun Oct 29 22:39:49 CST 2017
     */
    private static final long serialVersionUID = 1L;

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column se_public_permission.id
     *
     * @return the value of se_public_permission.id
     *
     * @mbggenerated Sun Oct 29 22:39:49 CST 2017
     */
    public Integer getId() {
        return id;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column se_public_permission.id
     *
     * @param id the value for se_public_permission.id
     *
     * @mbggenerated Sun Oct 29 22:39:49 CST 2017
     */
    public void setId(Integer id) {
        this.id = id;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column se_public_permission.resource
     *
     * @return the value of se_public_permission.resource
     *
     * @mbggenerated Sun Oct 29 22:39:49 CST 2017
     */
    public String getResource() {
        return resource;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column se_public_permission.resource
     *
     * @param resource the value for se_public_permission.resource
     *
     * @mbggenerated Sun Oct 29 22:39:49 CST 2017
     */
    public void setResource(String resource) {
        this.resource = resource == null ? null : resource.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column se_public_permission.filter
     *
     * @return the value of se_public_permission.filter
     *
     * @mbggenerated Sun Oct 29 22:39:49 CST 2017
     */
    public String getFilter() {
        return filter;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column se_public_permission.filter
     *
     * @param filter the value for se_public_permission.filter
     *
     * @mbggenerated Sun Oct 29 22:39:49 CST 2017
     */
    public void setFilter(String filter) {
        this.filter = filter == null ? null : filter.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column se_public_permission.system
     *
     * @return the value of se_public_permission.system
     *
     * @mbggenerated Sun Oct 29 22:39:49 CST 2017
     */
    public String getSystem() {
        return system;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column se_public_permission.system
     *
     * @param system the value for se_public_permission.system
     *
     * @mbggenerated Sun Oct 29 22:39:49 CST 2017
     */
    public void setSystem(String system) {
        this.system = system == null ? null : system.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column se_public_permission.comment
     *
     * @return the value of se_public_permission.comment
     *
     * @mbggenerated Sun Oct 29 22:39:49 CST 2017
     */
    public String getComment() {
        return comment;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column se_public_permission.comment
     *
     * @param comment the value for se_public_permission.comment
     *
     * @mbggenerated Sun Oct 29 22:39:49 CST 2017
     */
    public void setComment(String comment) {
        this.comment = comment == null ? null : comment.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table se_public_permission
     *
     * @mbggenerated Sun Oct 29 22:39:49 CST 2017
     */
    @Override
    public boolean equals(Object that) {
        if (this == that) {
            return true;
        }
        if (that == null) {
            return false;
        }
        if (getClass() != that.getClass()) {
            return false;
        }
        SePublicPermission other = (SePublicPermission) that;
        return (this.getId() == null ? other.getId() == null : this.getId().equals(other.getId()))
            && (this.getResource() == null ? other.getResource() == null : this.getResource().equals(other.getResource()))
            && (this.getFilter() == null ? other.getFilter() == null : this.getFilter().equals(other.getFilter()))
            && (this.getSystem() == null ? other.getSystem() == null : this.getSystem().equals(other.getSystem()))
            && (this.getComment() == null ? other.getComment() == null : this.getComment().equals(other.getComment()));
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table se_public_permission
     *
     * @mbggenerated Sun Oct 29 22:39:49 CST 2017
     */
    @Override
    public int hashCode() {
        final int prime = 31;
        int result = 1;
        result = prime * result + ((getId() == null) ? 0 : getId().hashCode());
        result = prime * result + ((getResource() == null) ? 0 : getResource().hashCode());
        result = prime * result + ((getFilter() == null) ? 0 : getFilter().hashCode());
        result = prime * result + ((getSystem() == null) ? 0 : getSystem().hashCode());
        result = prime * result + ((getComment() == null) ? 0 : getComment().hashCode());
        return result;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table se_public_permission
     *
     * @mbggenerated Sun Oct 29 22:39:49 CST 2017
     */
    @Override
    public String toString() {
        StringBuilder sb = new StringBuilder();
        sb.append(getClass().getSimpleName());
        sb.append(" [");
        sb.append("Hash = ").append(hashCode());
        sb.append(", id=").append(id);
        sb.append(", resource=").append(resource);
        sb.append(", filter=").append(filter);
        sb.append(", system=").append(system);
        sb.append(", comment=").append(comment);
        sb.append(", serialVersionUID=").append(serialVersionUID);
        sb.append("]");
        return sb.toString();
    }
}