package com.elichn.pub.core.model.pub.pojo.security;

import java.io.Serializable;

public class SeRescRoleKey implements Serializable {
    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column se_resc_role.resc_id
     *
     * @mbggenerated Sun Oct 29 22:40:02 CST 2017
     */
    private Integer rescId;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column se_resc_role.role_id
     *
     * @mbggenerated Sun Oct 29 22:40:02 CST 2017
     */
    private Integer roleId;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database table se_resc_role
     *
     * @mbggenerated Sun Oct 29 22:40:02 CST 2017
     */
    private static final long serialVersionUID = 1L;

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column se_resc_role.resc_id
     *
     * @return the value of se_resc_role.resc_id
     *
     * @mbggenerated Sun Oct 29 22:40:02 CST 2017
     */
    public Integer getRescId() {
        return rescId;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column se_resc_role.resc_id
     *
     * @param rescId the value for se_resc_role.resc_id
     *
     * @mbggenerated Sun Oct 29 22:40:02 CST 2017
     */
    public void setRescId(Integer rescId) {
        this.rescId = rescId;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column se_resc_role.role_id
     *
     * @return the value of se_resc_role.role_id
     *
     * @mbggenerated Sun Oct 29 22:40:02 CST 2017
     */
    public Integer getRoleId() {
        return roleId;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column se_resc_role.role_id
     *
     * @param roleId the value for se_resc_role.role_id
     *
     * @mbggenerated Sun Oct 29 22:40:02 CST 2017
     */
    public void setRoleId(Integer roleId) {
        this.roleId = roleId;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table se_resc_role
     *
     * @mbggenerated Sun Oct 29 22:40:02 CST 2017
     */
    @Override
    public boolean equals(Object that) {
        if (this == that) {
            return true;
        }
        if (that == null) {
            return false;
        }
        if (getClass() != that.getClass()) {
            return false;
        }
        SeRescRoleKey other = (SeRescRoleKey) that;
        return (this.getRescId() == null ? other.getRescId() == null : this.getRescId().equals(other.getRescId()))
            && (this.getRoleId() == null ? other.getRoleId() == null : this.getRoleId().equals(other.getRoleId()));
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table se_resc_role
     *
     * @mbggenerated Sun Oct 29 22:40:02 CST 2017
     */
    @Override
    public int hashCode() {
        final int prime = 31;
        int result = 1;
        result = prime * result + ((getRescId() == null) ? 0 : getRescId().hashCode());
        result = prime * result + ((getRoleId() == null) ? 0 : getRoleId().hashCode());
        return result;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table se_resc_role
     *
     * @mbggenerated Sun Oct 29 22:40:02 CST 2017
     */
    @Override
    public String toString() {
        StringBuilder sb = new StringBuilder();
        sb.append(getClass().getSimpleName());
        sb.append(" [");
        sb.append("Hash = ").append(hashCode());
        sb.append(", rescId=").append(rescId);
        sb.append(", roleId=").append(roleId);
        sb.append(", serialVersionUID=").append(serialVersionUID);
        sb.append("]");
        return sb.toString();
    }
}