package com.elichn.pub.core.model.pub.pojo.security;

import java.io.Serializable;
import org.joda.time.DateTime;

public class SeUser implements Serializable {
    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column se_user.id
     *
     * @mbggenerated Sun Oct 29 22:40:27 CST 2017
     */
    private Integer id;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column se_user.username
     *
     * @mbggenerated Sun Oct 29 22:40:27 CST 2017
     */
    private String username;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column se_user.cn_name
     *
     * @mbggenerated Sun Oct 29 22:40:27 CST 2017
     */
    private String cnName;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column se_user.password
     *
     * @mbggenerated Sun Oct 29 22:40:27 CST 2017
     */
    private String password;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column se_user.status
     *
     * @mbggenerated Sun Oct 29 22:40:27 CST 2017
     */
    private Integer status;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column se_user.user_type
     *
     * @mbggenerated Sun Oct 29 22:40:27 CST 2017
     */
    private Integer userType;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column se_user.descn
     *
     * @mbggenerated Sun Oct 29 22:40:27 CST 2017
     */
    private String descn;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column se_user.email
     *
     * @mbggenerated Sun Oct 29 22:40:27 CST 2017
     */
    private String email;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column se_user.create_time
     *
     * @mbggenerated Sun Oct 29 22:40:27 CST 2017
     */
    private DateTime createTime;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database table se_user
     *
     * @mbggenerated Sun Oct 29 22:40:27 CST 2017
     */
    private static final long serialVersionUID = 1L;

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column se_user.id
     *
     * @return the value of se_user.id
     *
     * @mbggenerated Sun Oct 29 22:40:27 CST 2017
     */
    public Integer getId() {
        return id;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column se_user.id
     *
     * @param id the value for se_user.id
     *
     * @mbggenerated Sun Oct 29 22:40:27 CST 2017
     */
    public void setId(Integer id) {
        this.id = id;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column se_user.username
     *
     * @return the value of se_user.username
     *
     * @mbggenerated Sun Oct 29 22:40:27 CST 2017
     */
    public String getUsername() {
        return username;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column se_user.username
     *
     * @param username the value for se_user.username
     *
     * @mbggenerated Sun Oct 29 22:40:27 CST 2017
     */
    public void setUsername(String username) {
        this.username = username == null ? null : username.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column se_user.cn_name
     *
     * @return the value of se_user.cn_name
     *
     * @mbggenerated Sun Oct 29 22:40:27 CST 2017
     */
    public String getCnName() {
        return cnName;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column se_user.cn_name
     *
     * @param cnName the value for se_user.cn_name
     *
     * @mbggenerated Sun Oct 29 22:40:27 CST 2017
     */
    public void setCnName(String cnName) {
        this.cnName = cnName == null ? null : cnName.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column se_user.password
     *
     * @return the value of se_user.password
     *
     * @mbggenerated Sun Oct 29 22:40:27 CST 2017
     */
    public String getPassword() {
        return password;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column se_user.password
     *
     * @param password the value for se_user.password
     *
     * @mbggenerated Sun Oct 29 22:40:27 CST 2017
     */
    public void setPassword(String password) {
        this.password = password == null ? null : password.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column se_user.status
     *
     * @return the value of se_user.status
     *
     * @mbggenerated Sun Oct 29 22:40:27 CST 2017
     */
    public Integer getStatus() {
        return status;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column se_user.status
     *
     * @param status the value for se_user.status
     *
     * @mbggenerated Sun Oct 29 22:40:27 CST 2017
     */
    public void setStatus(Integer status) {
        this.status = status;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column se_user.user_type
     *
     * @return the value of se_user.user_type
     *
     * @mbggenerated Sun Oct 29 22:40:27 CST 2017
     */
    public Integer getUserType() {
        return userType;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column se_user.user_type
     *
     * @param userType the value for se_user.user_type
     *
     * @mbggenerated Sun Oct 29 22:40:27 CST 2017
     */
    public void setUserType(Integer userType) {
        this.userType = userType;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column se_user.descn
     *
     * @return the value of se_user.descn
     *
     * @mbggenerated Sun Oct 29 22:40:27 CST 2017
     */
    public String getDescn() {
        return descn;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column se_user.descn
     *
     * @param descn the value for se_user.descn
     *
     * @mbggenerated Sun Oct 29 22:40:27 CST 2017
     */
    public void setDescn(String descn) {
        this.descn = descn == null ? null : descn.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column se_user.email
     *
     * @return the value of se_user.email
     *
     * @mbggenerated Sun Oct 29 22:40:27 CST 2017
     */
    public String getEmail() {
        return email;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column se_user.email
     *
     * @param email the value for se_user.email
     *
     * @mbggenerated Sun Oct 29 22:40:27 CST 2017
     */
    public void setEmail(String email) {
        this.email = email == null ? null : email.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column se_user.create_time
     *
     * @return the value of se_user.create_time
     *
     * @mbggenerated Sun Oct 29 22:40:27 CST 2017
     */
    public DateTime getCreateTime() {
        return createTime;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column se_user.create_time
     *
     * @param createTime the value for se_user.create_time
     *
     * @mbggenerated Sun Oct 29 22:40:27 CST 2017
     */
    public void setCreateTime(DateTime createTime) {
        this.createTime = createTime;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table se_user
     *
     * @mbggenerated Sun Oct 29 22:40:27 CST 2017
     */
    @Override
    public boolean equals(Object that) {
        if (this == that) {
            return true;
        }
        if (that == null) {
            return false;
        }
        if (getClass() != that.getClass()) {
            return false;
        }
        SeUser other = (SeUser) that;
        return (this.getId() == null ? other.getId() == null : this.getId().equals(other.getId()))
            && (this.getUsername() == null ? other.getUsername() == null : this.getUsername().equals(other.getUsername()))
            && (this.getCnName() == null ? other.getCnName() == null : this.getCnName().equals(other.getCnName()))
            && (this.getPassword() == null ? other.getPassword() == null : this.getPassword().equals(other.getPassword()))
            && (this.getStatus() == null ? other.getStatus() == null : this.getStatus().equals(other.getStatus()))
            && (this.getUserType() == null ? other.getUserType() == null : this.getUserType().equals(other.getUserType()))
            && (this.getDescn() == null ? other.getDescn() == null : this.getDescn().equals(other.getDescn()))
            && (this.getEmail() == null ? other.getEmail() == null : this.getEmail().equals(other.getEmail()))
            && (this.getCreateTime() == null ? other.getCreateTime() == null : this.getCreateTime().equals(other.getCreateTime()));
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table se_user
     *
     * @mbggenerated Sun Oct 29 22:40:27 CST 2017
     */
    @Override
    public int hashCode() {
        final int prime = 31;
        int result = 1;
        result = prime * result + ((getId() == null) ? 0 : getId().hashCode());
        result = prime * result + ((getUsername() == null) ? 0 : getUsername().hashCode());
        result = prime * result + ((getCnName() == null) ? 0 : getCnName().hashCode());
        result = prime * result + ((getPassword() == null) ? 0 : getPassword().hashCode());
        result = prime * result + ((getStatus() == null) ? 0 : getStatus().hashCode());
        result = prime * result + ((getUserType() == null) ? 0 : getUserType().hashCode());
        result = prime * result + ((getDescn() == null) ? 0 : getDescn().hashCode());
        result = prime * result + ((getEmail() == null) ? 0 : getEmail().hashCode());
        result = prime * result + ((getCreateTime() == null) ? 0 : getCreateTime().hashCode());
        return result;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table se_user
     *
     * @mbggenerated Sun Oct 29 22:40:27 CST 2017
     */
    @Override
    public String toString() {
        StringBuilder sb = new StringBuilder();
        sb.append(getClass().getSimpleName());
        sb.append(" [");
        sb.append("Hash = ").append(hashCode());
        sb.append(", id=").append(id);
        sb.append(", username=").append(username);
        sb.append(", cnName=").append(cnName);
        sb.append(", password=").append(password);
        sb.append(", status=").append(status);
        sb.append(", userType=").append(userType);
        sb.append(", descn=").append(descn);
        sb.append(", email=").append(email);
        sb.append(", createTime=").append(createTime);
        sb.append(", serialVersionUID=").append(serialVersionUID);
        sb.append("]");
        return sb.toString();
    }
}