package com.elichn.pub.core.model.pojo.security;

import java.io.Serializable;
import org.joda.time.DateTime;

public class SeHomePageNotice implements Serializable {
    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column se_home_page_notice.id
     *
     * @mbggenerated Sun Oct 29 22:39:28 CST 2017
     */
    private Integer id;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column se_home_page_notice.url
     *
     * @mbggenerated Sun Oct 29 22:39:28 CST 2017
     */
    private String url;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column se_home_page_notice.status
     *
     * @mbggenerated Sun Oct 29 22:39:28 CST 2017
     */
    private Integer status;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column se_home_page_notice.create_time
     *
     * @mbggenerated Sun Oct 29 22:39:28 CST 2017
     */
    private DateTime createTime;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column se_home_page_notice.update_time
     *
     * @mbggenerated Sun Oct 29 22:39:28 CST 2017
     */
    private DateTime updateTime;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column se_home_page_notice.type
     *
     * @mbggenerated Sun Oct 29 22:39:28 CST 2017
     */
    private Integer type;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column se_home_page_notice.content
     *
     * @mbggenerated Sun Oct 29 22:39:28 CST 2017
     */
    private String content;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database table se_home_page_notice
     *
     * @mbggenerated Sun Oct 29 22:39:28 CST 2017
     */
    private static final long serialVersionUID = 1L;

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column se_home_page_notice.id
     *
     * @return the value of se_home_page_notice.id
     *
     * @mbggenerated Sun Oct 29 22:39:28 CST 2017
     */
    public Integer getId() {
        return id;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column se_home_page_notice.id
     *
     * @param id the value for se_home_page_notice.id
     *
     * @mbggenerated Sun Oct 29 22:39:28 CST 2017
     */
    public void setId(Integer id) {
        this.id = id;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column se_home_page_notice.url
     *
     * @return the value of se_home_page_notice.url
     *
     * @mbggenerated Sun Oct 29 22:39:28 CST 2017
     */
    public String getUrl() {
        return url;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column se_home_page_notice.url
     *
     * @param url the value for se_home_page_notice.url
     *
     * @mbggenerated Sun Oct 29 22:39:28 CST 2017
     */
    public void setUrl(String url) {
        this.url = url == null ? null : url.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column se_home_page_notice.status
     *
     * @return the value of se_home_page_notice.status
     *
     * @mbggenerated Sun Oct 29 22:39:28 CST 2017
     */
    public Integer getStatus() {
        return status;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column se_home_page_notice.status
     *
     * @param status the value for se_home_page_notice.status
     *
     * @mbggenerated Sun Oct 29 22:39:28 CST 2017
     */
    public void setStatus(Integer status) {
        this.status = status;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column se_home_page_notice.create_time
     *
     * @return the value of se_home_page_notice.create_time
     *
     * @mbggenerated Sun Oct 29 22:39:28 CST 2017
     */
    public DateTime getCreateTime() {
        return createTime;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column se_home_page_notice.create_time
     *
     * @param createTime the value for se_home_page_notice.create_time
     *
     * @mbggenerated Sun Oct 29 22:39:28 CST 2017
     */
    public void setCreateTime(DateTime createTime) {
        this.createTime = createTime;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column se_home_page_notice.update_time
     *
     * @return the value of se_home_page_notice.update_time
     *
     * @mbggenerated Sun Oct 29 22:39:28 CST 2017
     */
    public DateTime getUpdateTime() {
        return updateTime;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column se_home_page_notice.update_time
     *
     * @param updateTime the value for se_home_page_notice.update_time
     *
     * @mbggenerated Sun Oct 29 22:39:28 CST 2017
     */
    public void setUpdateTime(DateTime updateTime) {
        this.updateTime = updateTime;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column se_home_page_notice.type
     *
     * @return the value of se_home_page_notice.type
     *
     * @mbggenerated Sun Oct 29 22:39:28 CST 2017
     */
    public Integer getType() {
        return type;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column se_home_page_notice.type
     *
     * @param type the value for se_home_page_notice.type
     *
     * @mbggenerated Sun Oct 29 22:39:28 CST 2017
     */
    public void setType(Integer type) {
        this.type = type;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column se_home_page_notice.content
     *
     * @return the value of se_home_page_notice.content
     *
     * @mbggenerated Sun Oct 29 22:39:28 CST 2017
     */
    public String getContent() {
        return content;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column se_home_page_notice.content
     *
     * @param content the value for se_home_page_notice.content
     *
     * @mbggenerated Sun Oct 29 22:39:28 CST 2017
     */
    public void setContent(String content) {
        this.content = content == null ? null : content.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table se_home_page_notice
     *
     * @mbggenerated Sun Oct 29 22:39:28 CST 2017
     */
    @Override
    public boolean equals(Object that) {
        if (this == that) {
            return true;
        }
        if (that == null) {
            return false;
        }
        if (getClass() != that.getClass()) {
            return false;
        }
        SeHomePageNotice other = (SeHomePageNotice) that;
        return (this.getId() == null ? other.getId() == null : this.getId().equals(other.getId()))
            && (this.getUrl() == null ? other.getUrl() == null : this.getUrl().equals(other.getUrl()))
            && (this.getStatus() == null ? other.getStatus() == null : this.getStatus().equals(other.getStatus()))
            && (this.getCreateTime() == null ? other.getCreateTime() == null : this.getCreateTime().equals(other.getCreateTime()))
            && (this.getUpdateTime() == null ? other.getUpdateTime() == null : this.getUpdateTime().equals(other.getUpdateTime()))
            && (this.getType() == null ? other.getType() == null : this.getType().equals(other.getType()))
            && (this.getContent() == null ? other.getContent() == null : this.getContent().equals(other.getContent()));
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table se_home_page_notice
     *
     * @mbggenerated Sun Oct 29 22:39:28 CST 2017
     */
    @Override
    public int hashCode() {
        final int prime = 31;
        int result = 1;
        result = prime * result + ((getId() == null) ? 0 : getId().hashCode());
        result = prime * result + ((getUrl() == null) ? 0 : getUrl().hashCode());
        result = prime * result + ((getStatus() == null) ? 0 : getStatus().hashCode());
        result = prime * result + ((getCreateTime() == null) ? 0 : getCreateTime().hashCode());
        result = prime * result + ((getUpdateTime() == null) ? 0 : getUpdateTime().hashCode());
        result = prime * result + ((getType() == null) ? 0 : getType().hashCode());
        result = prime * result + ((getContent() == null) ? 0 : getContent().hashCode());
        return result;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table se_home_page_notice
     *
     * @mbggenerated Sun Oct 29 22:39:28 CST 2017
     */
    @Override
    public String toString() {
        StringBuilder sb = new StringBuilder();
        sb.append(getClass().getSimpleName());
        sb.append(" [");
        sb.append("Hash = ").append(hashCode());
        sb.append(", id=").append(id);
        sb.append(", url=").append(url);
        sb.append(", status=").append(status);
        sb.append(", createTime=").append(createTime);
        sb.append(", updateTime=").append(updateTime);
        sb.append(", type=").append(type);
        sb.append(", content=").append(content);
        sb.append(", serialVersionUID=").append(serialVersionUID);
        sb.append("]");
        return sb.toString();
    }
}