package com.elichn.pub.core.model.pojo.security;

import java.io.Serializable;

public class SeRole implements Serializable {
    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column se_role.id
     *
     * @mbggenerated Sun Oct 29 22:40:08 CST 2017
     */
    private Integer id;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column se_role.role_name
     *
     * @mbggenerated Sun Oct 29 22:40:08 CST 2017
     */
    private String roleName;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column se_role.parent_id
     *
     * @mbggenerated Sun Oct 29 22:40:08 CST 2017
     */
    private Integer parentId;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column se_role.code
     *
     * @mbggenerated Sun Oct 29 22:40:08 CST 2017
     */
    private String code;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database table se_role
     *
     * @mbggenerated Sun Oct 29 22:40:08 CST 2017
     */
    private static final long serialVersionUID = 1L;

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column se_role.id
     *
     * @return the value of se_role.id
     *
     * @mbggenerated Sun Oct 29 22:40:08 CST 2017
     */
    public Integer getId() {
        return id;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column se_role.id
     *
     * @param id the value for se_role.id
     *
     * @mbggenerated Sun Oct 29 22:40:08 CST 2017
     */
    public void setId(Integer id) {
        this.id = id;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column se_role.role_name
     *
     * @return the value of se_role.role_name
     *
     * @mbggenerated Sun Oct 29 22:40:08 CST 2017
     */
    public String getRoleName() {
        return roleName;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column se_role.role_name
     *
     * @param roleName the value for se_role.role_name
     *
     * @mbggenerated Sun Oct 29 22:40:08 CST 2017
     */
    public void setRoleName(String roleName) {
        this.roleName = roleName == null ? null : roleName.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column se_role.parent_id
     *
     * @return the value of se_role.parent_id
     *
     * @mbggenerated Sun Oct 29 22:40:08 CST 2017
     */
    public Integer getParentId() {
        return parentId;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column se_role.parent_id
     *
     * @param parentId the value for se_role.parent_id
     *
     * @mbggenerated Sun Oct 29 22:40:08 CST 2017
     */
    public void setParentId(Integer parentId) {
        this.parentId = parentId;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column se_role.code
     *
     * @return the value of se_role.code
     *
     * @mbggenerated Sun Oct 29 22:40:08 CST 2017
     */
    public String getCode() {
        return code;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column se_role.code
     *
     * @param code the value for se_role.code
     *
     * @mbggenerated Sun Oct 29 22:40:08 CST 2017
     */
    public void setCode(String code) {
        this.code = code == null ? null : code.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table se_role
     *
     * @mbggenerated Sun Oct 29 22:40:08 CST 2017
     */
    @Override
    public boolean equals(Object that) {
        if (this == that) {
            return true;
        }
        if (that == null) {
            return false;
        }
        if (getClass() != that.getClass()) {
            return false;
        }
        SeRole other = (SeRole) that;
        return (this.getId() == null ? other.getId() == null : this.getId().equals(other.getId()))
            && (this.getRoleName() == null ? other.getRoleName() == null : this.getRoleName().equals(other.getRoleName()))
            && (this.getParentId() == null ? other.getParentId() == null : this.getParentId().equals(other.getParentId()))
            && (this.getCode() == null ? other.getCode() == null : this.getCode().equals(other.getCode()));
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table se_role
     *
     * @mbggenerated Sun Oct 29 22:40:08 CST 2017
     */
    @Override
    public int hashCode() {
        final int prime = 31;
        int result = 1;
        result = prime * result + ((getId() == null) ? 0 : getId().hashCode());
        result = prime * result + ((getRoleName() == null) ? 0 : getRoleName().hashCode());
        result = prime * result + ((getParentId() == null) ? 0 : getParentId().hashCode());
        result = prime * result + ((getCode() == null) ? 0 : getCode().hashCode());
        return result;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table se_role
     *
     * @mbggenerated Sun Oct 29 22:40:08 CST 2017
     */
    @Override
    public String toString() {
        StringBuilder sb = new StringBuilder();
        sb.append(getClass().getSimpleName());
        sb.append(" [");
        sb.append("Hash = ").append(hashCode());
        sb.append(", id=").append(id);
        sb.append(", roleName=").append(roleName);
        sb.append(", parentId=").append(parentId);
        sb.append(", code=").append(code);
        sb.append(", serialVersionUID=").append(serialVersionUID);
        sb.append("]");
        return sb.toString();
    }
}