package com.elichn.pub.core.model.pojo.security;

import java.io.Serializable;

public class SeRoleNotice implements Serializable {
    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column se_role_notice.id
     *
     * @mbggenerated Sun Oct 29 22:40:20 CST 2017
     */
    private Integer id;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column se_role_notice.role_id
     *
     * @mbggenerated Sun Oct 29 22:40:20 CST 2017
     */
    private Integer roleId;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column se_role_notice.notice_id
     *
     * @mbggenerated Sun Oct 29 22:40:20 CST 2017
     */
    private Integer noticeId;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database table se_role_notice
     *
     * @mbggenerated Sun Oct 29 22:40:20 CST 2017
     */
    private static final long serialVersionUID = 1L;

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column se_role_notice.id
     *
     * @return the value of se_role_notice.id
     *
     * @mbggenerated Sun Oct 29 22:40:20 CST 2017
     */
    public Integer getId() {
        return id;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column se_role_notice.id
     *
     * @param id the value for se_role_notice.id
     *
     * @mbggenerated Sun Oct 29 22:40:20 CST 2017
     */
    public void setId(Integer id) {
        this.id = id;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column se_role_notice.role_id
     *
     * @return the value of se_role_notice.role_id
     *
     * @mbggenerated Sun Oct 29 22:40:20 CST 2017
     */
    public Integer getRoleId() {
        return roleId;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column se_role_notice.role_id
     *
     * @param roleId the value for se_role_notice.role_id
     *
     * @mbggenerated Sun Oct 29 22:40:20 CST 2017
     */
    public void setRoleId(Integer roleId) {
        this.roleId = roleId;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column se_role_notice.notice_id
     *
     * @return the value of se_role_notice.notice_id
     *
     * @mbggenerated Sun Oct 29 22:40:20 CST 2017
     */
    public Integer getNoticeId() {
        return noticeId;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column se_role_notice.notice_id
     *
     * @param noticeId the value for se_role_notice.notice_id
     *
     * @mbggenerated Sun Oct 29 22:40:20 CST 2017
     */
    public void setNoticeId(Integer noticeId) {
        this.noticeId = noticeId;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table se_role_notice
     *
     * @mbggenerated Sun Oct 29 22:40:20 CST 2017
     */
    @Override
    public boolean equals(Object that) {
        if (this == that) {
            return true;
        }
        if (that == null) {
            return false;
        }
        if (getClass() != that.getClass()) {
            return false;
        }
        SeRoleNotice other = (SeRoleNotice) that;
        return (this.getId() == null ? other.getId() == null : this.getId().equals(other.getId()))
            && (this.getRoleId() == null ? other.getRoleId() == null : this.getRoleId().equals(other.getRoleId()))
            && (this.getNoticeId() == null ? other.getNoticeId() == null : this.getNoticeId().equals(other.getNoticeId()));
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table se_role_notice
     *
     * @mbggenerated Sun Oct 29 22:40:20 CST 2017
     */
    @Override
    public int hashCode() {
        final int prime = 31;
        int result = 1;
        result = prime * result + ((getId() == null) ? 0 : getId().hashCode());
        result = prime * result + ((getRoleId() == null) ? 0 : getRoleId().hashCode());
        result = prime * result + ((getNoticeId() == null) ? 0 : getNoticeId().hashCode());
        return result;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table se_role_notice
     *
     * @mbggenerated Sun Oct 29 22:40:20 CST 2017
     */
    @Override
    public String toString() {
        StringBuilder sb = new StringBuilder();
        sb.append(getClass().getSimpleName());
        sb.append(" [");
        sb.append("Hash = ").append(hashCode());
        sb.append(", id=").append(id);
        sb.append(", roleId=").append(roleId);
        sb.append(", noticeId=").append(noticeId);
        sb.append(", serialVersionUID=").append(serialVersionUID);
        sb.append("]");
        return sb.toString();
    }
}