package com.elichn.pub.core.model.mapper.security;

import com.elichn.pub.core.model.pojo.security.SeHomePageNotice;
import com.elichn.pub.core.model.pojo.security.SeHomePageNoticeExample;
import java.util.List;
import org.apache.ibatis.annotations.Delete;
import org.apache.ibatis.annotations.Insert;
import org.apache.ibatis.annotations.Param;
import org.apache.ibatis.annotations.ResultMap;
import org.apache.ibatis.annotations.Select;
import org.apache.ibatis.annotations.SelectKey;
import org.apache.ibatis.annotations.Update;

public interface SeHomePageNoticeMapper {
    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table se_home_page_notice
     *
     * @mbggenerated Sun Oct 29 22:39:28 CST 2017
     */
    int countByExample(SeHomePageNoticeExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table se_home_page_notice
     *
     * @mbggenerated Sun Oct 29 22:39:28 CST 2017
     */
    int deleteByExample(SeHomePageNoticeExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table se_home_page_notice
     *
     * @mbggenerated Sun Oct 29 22:39:28 CST 2017
     */
    @Delete({
        "delete from se_home_page_notice",
        "where id = #{id,jdbcType=INTEGER}"
    })
    int deleteByPrimaryKey(Integer id);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table se_home_page_notice
     *
     * @mbggenerated Sun Oct 29 22:39:28 CST 2017
     */
    @Insert({
        "insert into se_home_page_notice (url, status, ",
        "create_time, ",
        "update_time, ",
        "type, content)",
        "values (#{url,jdbcType=VARCHAR}, #{status,jdbcType=INTEGER}, ",
        "#{createTime,jdbcType=TIMESTAMP,typeHandler=com.elichn.mybatis.typehandler.JodaDateTime2TimestampTypeHandler}, ",
        "#{updateTime,jdbcType=TIMESTAMP,typeHandler=com.elichn.mybatis.typehandler.JodaDateTime2TimestampTypeHandler}, ",
        "#{type,jdbcType=INTEGER}, #{content,jdbcType=LONGVARCHAR})"
    })
    @SelectKey(statement="SELECT LAST_INSERT_ID()", keyProperty="id", before=false, resultType=Integer.class)
    int insert(SeHomePageNotice record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table se_home_page_notice
     *
     * @mbggenerated Sun Oct 29 22:39:28 CST 2017
     */
    int insertSelective(SeHomePageNotice record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table se_home_page_notice
     *
     * @mbggenerated Sun Oct 29 22:39:28 CST 2017
     */
    List<SeHomePageNotice> selectByExampleWithBLOBs(SeHomePageNoticeExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table se_home_page_notice
     *
     * @mbggenerated Sun Oct 29 22:39:28 CST 2017
     */
    List<SeHomePageNotice> selectByExample(SeHomePageNoticeExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table se_home_page_notice
     *
     * @mbggenerated Sun Oct 29 22:39:28 CST 2017
     */
    @Select({
        "select",
        "id, url, status, create_time, update_time, type, content",
        "from se_home_page_notice",
        "where id = #{id,jdbcType=INTEGER}"
    })
    @ResultMap("ResultMapWithBLOBs")
    SeHomePageNotice selectByPrimaryKey(Integer id);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table se_home_page_notice
     *
     * @mbggenerated Sun Oct 29 22:39:28 CST 2017
     */
    int updateByExampleSelective(@Param("record") SeHomePageNotice record, @Param("example") SeHomePageNoticeExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table se_home_page_notice
     *
     * @mbggenerated Sun Oct 29 22:39:28 CST 2017
     */
    int updateByExampleWithBLOBs(@Param("record") SeHomePageNotice record, @Param("example") SeHomePageNoticeExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table se_home_page_notice
     *
     * @mbggenerated Sun Oct 29 22:39:28 CST 2017
     */
    int updateByExample(@Param("record") SeHomePageNotice record, @Param("example") SeHomePageNoticeExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table se_home_page_notice
     *
     * @mbggenerated Sun Oct 29 22:39:28 CST 2017
     */
    int updateByPrimaryKeySelective(SeHomePageNotice record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table se_home_page_notice
     *
     * @mbggenerated Sun Oct 29 22:39:28 CST 2017
     */
    @Update({
        "update se_home_page_notice",
        "set url = #{url,jdbcType=VARCHAR},",
          "status = #{status,jdbcType=INTEGER},",
          "create_time = #{createTime,jdbcType=TIMESTAMP,typeHandler=com.elichn.mybatis.typehandler.JodaDateTime2TimestampTypeHandler},",
          "update_time = #{updateTime,jdbcType=TIMESTAMP,typeHandler=com.elichn.mybatis.typehandler.JodaDateTime2TimestampTypeHandler},",
          "type = #{type,jdbcType=INTEGER},",
          "content = #{content,jdbcType=LONGVARCHAR}",
        "where id = #{id,jdbcType=INTEGER}"
    })
    int updateByPrimaryKeyWithBLOBs(SeHomePageNotice record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table se_home_page_notice
     *
     * @mbggenerated Sun Oct 29 22:39:28 CST 2017
     */
    @Update({
        "update se_home_page_notice",
        "set url = #{url,jdbcType=VARCHAR},",
          "status = #{status,jdbcType=INTEGER},",
          "create_time = #{createTime,jdbcType=TIMESTAMP,typeHandler=com.elichn.mybatis.typehandler.JodaDateTime2TimestampTypeHandler},",
          "update_time = #{updateTime,jdbcType=TIMESTAMP,typeHandler=com.elichn.mybatis.typehandler.JodaDateTime2TimestampTypeHandler},",
          "type = #{type,jdbcType=INTEGER}",
        "where id = #{id,jdbcType=INTEGER}"
    })
    int updateByPrimaryKey(SeHomePageNotice record);
}