package com.elichn.pub.core.model.mapper.security;

import com.elichn.pub.core.model.pojo.security.SePublicPermission;
import com.elichn.pub.core.model.pojo.security.SePublicPermissionExample;

import java.util.List;
import org.apache.ibatis.annotations.Delete;
import org.apache.ibatis.annotations.Insert;
import org.apache.ibatis.annotations.Param;
import org.apache.ibatis.annotations.ResultMap;
import org.apache.ibatis.annotations.Select;
import org.apache.ibatis.annotations.SelectKey;
import org.apache.ibatis.annotations.Update;

public interface SePublicPermissionMapper {
    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table se_public_permission
     *
     * @mbggenerated Sun Oct 29 22:39:49 CST 2017
     */
    int countByExample(SePublicPermissionExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table se_public_permission
     *
     * @mbggenerated Sun Oct 29 22:39:49 CST 2017
     */
    int deleteByExample(SePublicPermissionExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table se_public_permission
     *
     * @mbggenerated Sun Oct 29 22:39:49 CST 2017
     */
    @Delete({
        "delete from se_public_permission",
        "where id = #{id,jdbcType=INTEGER}"
    })
    int deleteByPrimaryKey(Integer id);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table se_public_permission
     *
     * @mbggenerated Sun Oct 29 22:39:49 CST 2017
     */
    @Insert({
        "insert into se_public_permission (resource, filter, ",
        "system, comment)",
        "values (#{resource,jdbcType=VARCHAR}, #{filter,jdbcType=VARCHAR}, ",
        "#{system,jdbcType=VARCHAR}, #{comment,jdbcType=VARCHAR})"
    })
    @SelectKey(statement="SELECT LAST_INSERT_ID()", keyProperty="id", before=false, resultType=Integer.class)
    int insert(SePublicPermission record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table se_public_permission
     *
     * @mbggenerated Sun Oct 29 22:39:49 CST 2017
     */
    int insertSelective(SePublicPermission record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table se_public_permission
     *
     * @mbggenerated Sun Oct 29 22:39:49 CST 2017
     */
    List<SePublicPermission> selectByExample(SePublicPermissionExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table se_public_permission
     *
     * @mbggenerated Sun Oct 29 22:39:49 CST 2017
     */
    @Select({
        "select",
        "id, resource, filter, system, comment",
        "from se_public_permission",
        "where id = #{id,jdbcType=INTEGER}"
    })
    @ResultMap("BaseResultMap")
    SePublicPermission selectByPrimaryKey(Integer id);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table se_public_permission
     *
     * @mbggenerated Sun Oct 29 22:39:49 CST 2017
     */
    int updateByExampleSelective(@Param("record") SePublicPermission record, @Param("example") SePublicPermissionExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table se_public_permission
     *
     * @mbggenerated Sun Oct 29 22:39:49 CST 2017
     */
    int updateByExample(@Param("record") SePublicPermission record, @Param("example") SePublicPermissionExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table se_public_permission
     *
     * @mbggenerated Sun Oct 29 22:39:49 CST 2017
     */
    int updateByPrimaryKeySelective(SePublicPermission record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table se_public_permission
     *
     * @mbggenerated Sun Oct 29 22:39:49 CST 2017
     */
    @Update({
        "update se_public_permission",
        "set resource = #{resource,jdbcType=VARCHAR},",
          "filter = #{filter,jdbcType=VARCHAR},",
          "system = #{system,jdbcType=VARCHAR},",
          "comment = #{comment,jdbcType=VARCHAR}",
        "where id = #{id,jdbcType=INTEGER}"
    })
    int updateByPrimaryKey(SePublicPermission record);
}