package com.elichn.pub.core.model.pub.mapper.security;

import com.elichn.pub.core.model.pub.pojo.security.SeLog;
import com.elichn.pub.core.model.pub.pojo.security.SeLogExample;
import java.util.List;
import org.apache.ibatis.annotations.Delete;
import org.apache.ibatis.annotations.Insert;
import org.apache.ibatis.annotations.Param;
import org.apache.ibatis.annotations.ResultMap;
import org.apache.ibatis.annotations.Select;
import org.apache.ibatis.annotations.SelectKey;
import org.apache.ibatis.annotations.Update;

public interface SeLogMapper {
    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table se_log
     *
     * @mbggenerated Sun Oct 29 22:39:39 CST 2017
     */
    int countByExample(SeLogExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table se_log
     *
     * @mbggenerated Sun Oct 29 22:39:39 CST 2017
     */
    int deleteByExample(SeLogExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table se_log
     *
     * @mbggenerated Sun Oct 29 22:39:39 CST 2017
     */
    @Delete({
        "delete from se_log",
        "where id = #{id,jdbcType=INTEGER}"
    })
    int deleteByPrimaryKey(Integer id);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table se_log
     *
     * @mbggenerated Sun Oct 29 22:39:39 CST 2017
     */
    @Insert({
        "insert into se_log (ip, user_name, ",
        "log_type, log_content, ",
        "log_time)",
        "values (#{ip,jdbcType=VARCHAR}, #{userName,jdbcType=VARCHAR}, ",
        "#{logType,jdbcType=VARCHAR}, #{logContent,jdbcType=VARCHAR}, ",
        "#{logTime,jdbcType=TIMESTAMP,typeHandler=com.elichn.mybatis.typehandler.JodaDateTime2TimestampTypeHandler})"
    })
    @SelectKey(statement="SELECT LAST_INSERT_ID()", keyProperty="id", before=false, resultType=Integer.class)
    int insert(SeLog record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table se_log
     *
     * @mbggenerated Sun Oct 29 22:39:39 CST 2017
     */
    int insertSelective(SeLog record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table se_log
     *
     * @mbggenerated Sun Oct 29 22:39:39 CST 2017
     */
    List<SeLog> selectByExample(SeLogExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table se_log
     *
     * @mbggenerated Sun Oct 29 22:39:39 CST 2017
     */
    @Select({
        "select",
        "id, ip, user_name, log_type, log_content, log_time",
        "from se_log",
        "where id = #{id,jdbcType=INTEGER}"
    })
    @ResultMap("BaseResultMap")
    SeLog selectByPrimaryKey(Integer id);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table se_log
     *
     * @mbggenerated Sun Oct 29 22:39:39 CST 2017
     */
    int updateByExampleSelective(@Param("record") SeLog record, @Param("example") SeLogExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table se_log
     *
     * @mbggenerated Sun Oct 29 22:39:39 CST 2017
     */
    int updateByExample(@Param("record") SeLog record, @Param("example") SeLogExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table se_log
     *
     * @mbggenerated Sun Oct 29 22:39:39 CST 2017
     */
    int updateByPrimaryKeySelective(SeLog record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table se_log
     *
     * @mbggenerated Sun Oct 29 22:39:39 CST 2017
     */
    @Update({
        "update se_log",
        "set ip = #{ip,jdbcType=VARCHAR},",
          "user_name = #{userName,jdbcType=VARCHAR},",
          "log_type = #{logType,jdbcType=VARCHAR},",
          "log_content = #{logContent,jdbcType=VARCHAR},",
          "log_time = #{logTime,jdbcType=TIMESTAMP,typeHandler=com.elichn.mybatis.typehandler.JodaDateTime2TimestampTypeHandler}",
        "where id = #{id,jdbcType=INTEGER}"
    })
    int updateByPrimaryKey(SeLog record);
}