package com.elichn.pub.core.model.pub.mapper.security;

import com.elichn.pub.core.model.pub.pojo.security.SeResc;
import com.elichn.pub.core.model.pub.pojo.security.SeRescExample;
import java.util.List;
import org.apache.ibatis.annotations.Delete;
import org.apache.ibatis.annotations.Insert;
import org.apache.ibatis.annotations.Param;
import org.apache.ibatis.annotations.ResultMap;
import org.apache.ibatis.annotations.Select;
import org.apache.ibatis.annotations.SelectKey;
import org.apache.ibatis.annotations.Update;

public interface SeRescMapper {
    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table se_resc
     *
     * @mbggenerated Sun Oct 29 22:39:56 CST 2017
     */
    int countByExample(SeRescExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table se_resc
     *
     * @mbggenerated Sun Oct 29 22:39:56 CST 2017
     */
    int deleteByExample(SeRescExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table se_resc
     *
     * @mbggenerated Sun Oct 29 22:39:56 CST 2017
     */
    @Delete({
        "delete from se_resc",
        "where id = #{id,jdbcType=INTEGER}"
    })
    int deleteByPrimaryKey(Integer id);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table se_resc
     *
     * @mbggenerated Sun Oct 29 22:39:56 CST 2017
     */
    @Insert({
        "insert into se_resc (name, show_url, ",
        "res_string, priority, ",
        "descn, father_id, ",
        "show_menu, module_id)",
        "values (#{name,jdbcType=VARCHAR}, #{showUrl,jdbcType=VARCHAR}, ",
        "#{resString,jdbcType=VARCHAR}, #{priority,jdbcType=INTEGER}, ",
        "#{descn,jdbcType=VARCHAR}, #{fatherId,jdbcType=INTEGER}, ",
        "#{showMenu,jdbcType=INTEGER}, #{moduleId,jdbcType=INTEGER})"
    })
    @SelectKey(statement="SELECT LAST_INSERT_ID()", keyProperty="id", before=false, resultType=Integer.class)
    int insert(SeResc record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table se_resc
     *
     * @mbggenerated Sun Oct 29 22:39:56 CST 2017
     */
    int insertSelective(SeResc record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table se_resc
     *
     * @mbggenerated Sun Oct 29 22:39:56 CST 2017
     */
    List<SeResc> selectByExample(SeRescExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table se_resc
     *
     * @mbggenerated Sun Oct 29 22:39:56 CST 2017
     */
    @Select({
        "select",
        "id, name, show_url, res_string, priority, descn, father_id, show_menu, module_id",
        "from se_resc",
        "where id = #{id,jdbcType=INTEGER}"
    })
    @ResultMap("BaseResultMap")
    SeResc selectByPrimaryKey(Integer id);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table se_resc
     *
     * @mbggenerated Sun Oct 29 22:39:56 CST 2017
     */
    int updateByExampleSelective(@Param("record") SeResc record, @Param("example") SeRescExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table se_resc
     *
     * @mbggenerated Sun Oct 29 22:39:56 CST 2017
     */
    int updateByExample(@Param("record") SeResc record, @Param("example") SeRescExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table se_resc
     *
     * @mbggenerated Sun Oct 29 22:39:56 CST 2017
     */
    int updateByPrimaryKeySelective(SeResc record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table se_resc
     *
     * @mbggenerated Sun Oct 29 22:39:56 CST 2017
     */
    @Update({
        "update se_resc",
        "set name = #{name,jdbcType=VARCHAR},",
          "show_url = #{showUrl,jdbcType=VARCHAR},",
          "res_string = #{resString,jdbcType=VARCHAR},",
          "priority = #{priority,jdbcType=INTEGER},",
          "descn = #{descn,jdbcType=VARCHAR},",
          "father_id = #{fatherId,jdbcType=INTEGER},",
          "show_menu = #{showMenu,jdbcType=INTEGER},",
          "module_id = #{moduleId,jdbcType=INTEGER}",
        "where id = #{id,jdbcType=INTEGER}"
    })
    int updateByPrimaryKey(SeResc record);
}