package com.elichn.pub.core.model.pub.mapper.security;

import com.elichn.pub.core.model.pub.pojo.security.SeRole;
import com.elichn.pub.core.model.pub.pojo.security.SeRoleExample;
import java.util.List;
import org.apache.ibatis.annotations.Delete;
import org.apache.ibatis.annotations.Insert;
import org.apache.ibatis.annotations.Param;
import org.apache.ibatis.annotations.ResultMap;
import org.apache.ibatis.annotations.Select;
import org.apache.ibatis.annotations.SelectKey;
import org.apache.ibatis.annotations.Update;

public interface SeRoleMapper {
    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table se_role
     *
     * @mbggenerated Sun Oct 29 22:40:08 CST 2017
     */
    int countByExample(SeRoleExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table se_role
     *
     * @mbggenerated Sun Oct 29 22:40:08 CST 2017
     */
    int deleteByExample(SeRoleExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table se_role
     *
     * @mbggenerated Sun Oct 29 22:40:08 CST 2017
     */
    @Delete({
        "delete from se_role",
        "where id = #{id,jdbcType=INTEGER}"
    })
    int deleteByPrimaryKey(Integer id);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table se_role
     *
     * @mbggenerated Sun Oct 29 22:40:08 CST 2017
     */
    @Insert({
        "insert into se_role (role_name, parent_id, ",
        "code)",
        "values (#{roleName,jdbcType=VARCHAR}, #{parentId,jdbcType=INTEGER}, ",
        "#{code,jdbcType=VARCHAR})"
    })
    @SelectKey(statement="SELECT LAST_INSERT_ID()", keyProperty="id", before=false, resultType=Integer.class)
    int insert(SeRole record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table se_role
     *
     * @mbggenerated Sun Oct 29 22:40:08 CST 2017
     */
    int insertSelective(SeRole record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table se_role
     *
     * @mbggenerated Sun Oct 29 22:40:08 CST 2017
     */
    List<SeRole> selectByExample(SeRoleExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table se_role
     *
     * @mbggenerated Sun Oct 29 22:40:08 CST 2017
     */
    @Select({
        "select",
        "id, role_name, parent_id, code",
        "from se_role",
        "where id = #{id,jdbcType=INTEGER}"
    })
    @ResultMap("BaseResultMap")
    SeRole selectByPrimaryKey(Integer id);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table se_role
     *
     * @mbggenerated Sun Oct 29 22:40:08 CST 2017
     */
    int updateByExampleSelective(@Param("record") SeRole record, @Param("example") SeRoleExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table se_role
     *
     * @mbggenerated Sun Oct 29 22:40:08 CST 2017
     */
    int updateByExample(@Param("record") SeRole record, @Param("example") SeRoleExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table se_role
     *
     * @mbggenerated Sun Oct 29 22:40:08 CST 2017
     */
    int updateByPrimaryKeySelective(SeRole record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table se_role
     *
     * @mbggenerated Sun Oct 29 22:40:08 CST 2017
     */
    @Update({
        "update se_role",
        "set role_name = #{roleName,jdbcType=VARCHAR},",
          "parent_id = #{parentId,jdbcType=INTEGER},",
          "code = #{code,jdbcType=VARCHAR}",
        "where id = #{id,jdbcType=INTEGER}"
    })
    int updateByPrimaryKey(SeRole record);
}