package com.elichn.pub.core.model.pub.mapper.security;

import com.elichn.pub.core.model.pub.pojo.security.SeUserRoleExample;
import com.elichn.pub.core.model.pub.pojo.security.SeUserRoleKey;
import java.util.List;
import org.apache.ibatis.annotations.Delete;
import org.apache.ibatis.annotations.Insert;
import org.apache.ibatis.annotations.Param;

public interface SeUserRoleMapper {
    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table se_user_role
     *
     * @mbggenerated Sun Oct 29 22:40:33 CST 2017
     */
    int countByExample(SeUserRoleExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table se_user_role
     *
     * @mbggenerated Sun Oct 29 22:40:33 CST 2017
     */
    int deleteByExample(SeUserRoleExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table se_user_role
     *
     * @mbggenerated Sun Oct 29 22:40:33 CST 2017
     */
    @Delete({
        "delete from se_user_role",
        "where user_id = #{userId,jdbcType=INTEGER}",
          "and role_id = #{roleId,jdbcType=INTEGER}"
    })
    int deleteByPrimaryKey(SeUserRoleKey key);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table se_user_role
     *
     * @mbggenerated Sun Oct 29 22:40:33 CST 2017
     */
    @Insert({
        "insert into se_user_role (user_id, role_id)",
        "values (#{userId,jdbcType=INTEGER}, #{roleId,jdbcType=INTEGER})"
    })
    int insert(SeUserRoleKey record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table se_user_role
     *
     * @mbggenerated Sun Oct 29 22:40:33 CST 2017
     */
    int insertSelective(SeUserRoleKey record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table se_user_role
     *
     * @mbggenerated Sun Oct 29 22:40:33 CST 2017
     */
    List<SeUserRoleKey> selectByExample(SeUserRoleExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table se_user_role
     *
     * @mbggenerated Sun Oct 29 22:40:33 CST 2017
     */
    int updateByExampleSelective(@Param("record") SeUserRoleKey record, @Param("example") SeUserRoleExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table se_user_role
     *
     * @mbggenerated Sun Oct 29 22:40:33 CST 2017
     */
    int updateByExample(@Param("record") SeUserRoleKey record, @Param("example") SeUserRoleExample example);
}